# default.conf
server {
    listen       8080;  # 원래 80이었던 것을 8080으로 변경!
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
}